### ISSUE TITLE
Need to expose a method to return the underlying native node

### ISSUE THREAD

**Issue by billorcutt** [billorcutt/i_dropped_my_phone_the_screen_cracked#3]
Interfacing with native nodes or other plugin/modules

**Comment by jimkang** [comment]
Did this ever get created? I'm interested in connecting nodes made natively to nodes made from cracked.

**Comment by billorcutt** [comment]
No I decided this was a bad idea. What native node to you want to connect to?

**Comment by jimkang** [comment]
Anything I happen to find in another library outside of the cracked ecosystem.

**Comment by billorcutt** [comment]
Cracked is a wrapper around native web audio nodes. Not all nodes have been wrapped, so if there's something missing let me know and I can look at updating the library to include it.

**Comment by jimkang** [comment]
Thanks.

One downside with this is that you have to commit to using Cracked and nothing else or just decide to not use Cracked. I understand you may have already thought about this and decided it's fine, but just in case, there it is.
