### ISSUE TITLE
method to list existing nodes by selector

### ISSUE THREAD

**Issue by jamesstaub** [billorcutt/i_dropped_my_phone_the_screen_cracked#37]
Hi Bill

Is it possible to return a list of any existing cracked nodes as the result of a query? 

if I've created a bunch of nodes like `__().sine({id:'sine1', class:'osc'})` throughout my app, it would be very useful to be able to call `__('sine')` or `__('.osc')` and have a property on the returned cracked object with a list of any existing nodes matching that query. (thinking similar to jQuery). 

I'm creating an app that requires initializing and tearing down audio nodes at various points, so it would be useful to have this feature to validate that there are not orphaned nodes hanging around.

**Comment by billorcutt** [comment]
There's a method called `each()` that takes a callback and iterates over the currently selected nodes. You can see it in the synth plugin - https://goo.gl/GDaw2k - where I'm doing dynamic voice allocation. It's a messy approach though and I'm reluctant to offer it as an example. Can you share more about your use case? Any method called on a selection should operate on every selected node without having to manually manage it

**Comment by jamesstaub** [comment]
I'm using Ember.js to build an interface for a multitrack drum sequencer type thing and I am trying to better manage the creation + cleanup of nodes. 

On each track I am creating a chain of nodes like so
`__().sampler({id:trackId}).compressor().gain().connect('#outputNode')`

Various interactions cause the ember component to re-render, which then reinitializes the cracked nodes.  My current strategy is to assign an ID to every cracked node I create, and keep track of them in a list so i can tear them down individually when the component re-renders. 

I was mostly just looking for a way to query a cracked selector and see a list of existing nodes, in order to verify that I am successfully cleaning everything up on each re-render.

I'm using firefox's web audio inspector to keep track of the audio nodes that are being created. 
When I call  `__(selector).unbind("step");` and `__(selector).remove()`, I see the nodes disconnect in the the audio inspector, but they appear to hang around in a disconnected state. (see the 6 disconnected nodes above the connected chain in this screenshot) 

![screen shot 2017-12-19 at 11 24 59 am](https://user-images.githubusercontent.com/1205113/34167418-c12cf0bc-e4af-11e7-942a-b165a974d7e6.png)


calling `.each()` seems like it will be a little easier than my current approach of looping over a list of cracked id's.

**Comment by billorcutt** [comment]
I think you have to wait for garbage collection to run to see them disappear from the web audio inspector. Testing now with your code and after a minute or so the nodes disappear once gc runs. If you can avoid it, I'd avoid manually messing w/ nodes... 

https://rawgit.com/billorcutt/da4dd18353aae41cec2ac6c3f522307c/raw/5a6502be7747e6169d6bd67e987e37b9b973877d/node_removal.html

**Comment by jamesstaub** [comment]
got it, thanks a lot.
