### ISSUE TITLE
cant use `.connect()` in macro

### ISSUE THREAD

**Issue by jamesstaub** [billorcutt/i_dropped_my_phone_the_screen_cracked#48]
I'm trying to create a macro like this but it doesn't seem to work.

```
cracked.microsynth = function(params) {
    __().begin("channelOut").gain(1).panner().connect('dac').end("channelOut");
    return cracked;
}
```

is there some inherent reason why `.connect` might not work inside a macro?

**Comment by billorcutt** [comment]
I see you closed it, so maybe you figured it out, but for anyone poking around, I'll answer it anyway. You can use `.connect` in a macro no problem. Check out the source for Ring Modulator for an example: https://bit.ly/2VVL0ax 

The problem in the code you posted is `__()` at the beginning which when called w/o parameters clears the current context, not what you want in this situation. Just use the name `__` instead. 

```
cracked.channelOut = function(params) {
    __.begin("channelOut").gain(1).panner().connect('dac').end("channelOut");
    return cracked;
}

__().sine().channelOut().dac().play()
```

**Comment by jamesstaub** [comment]
aha, didn't realize that about the params. thanks!

sorry for the double post, weird thing with github drafts

**Comment by jamesstaub** [comment]
sorry one more question: is it true that `connect()` only works in a macro if you're connecting to nodes that are created inside the macro?

here's the expanded version of what I'm trying to do. when I look at the web audio graph the panners do not seem to get connected to the '#master-compressor

```
__().compressor({  id: 'master-compressor' }).dac();

cracked.channelOut = function(params) {
    __.begin('channelOut', params).gain(1).panner().connect('#master-compressor').end('channelOut');
    return cracked;
}

__().sampler({...}).channelOut()
__().sampler({...}).channelOut()
__().sampler({...}).channelOut()
```

**Comment by billorcutt** [comment]
That's right

**Comment by billorcutt** [comment]
That's right, macros should be self-contained. Just use the output from the macro to connect to the compressor:
`__().sampler({...}).channelOut().compressor().dac()` or `__().sampler({...}).channelOut().connect("#master-compressor")`

**Comment by jamesstaub** [comment]
ok great thanks for clarification
